version: '3'
services:
    board:
        image: simple-board:latest
        environment:
            - FLASK_ENV=prod
            - POSTGRES_HOST=127.0.0.1
            - POSTGRES_PORT=5432
            - POSTGRES_USER=developer
            - POSTGRES_DB_NAME=developer
            - POSTGRES_PASSWORD=devpassword
            - USER_JWT_SECRET_KEY=qwerasdfzxcv1234
        ports:
            - "127.0.0.1:5000:5000"
        depends_on:
            - postgres
    postgres:
        image: postgres:10
        environment:
            - POSTGRES_DB=developer
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=devpassword
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:25000:5432"
    redis:
        image: redis:latest
        ports:
            - "127.0.0.1:25100:6379"
        command: redis-server --save ""

volumes:
    postgres-data:
        driver: local