"""empty message

Revision ID: 246f9ed98851
Revises: f902d969c141
Create Date: 2020-09-06 19:07:49.490589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246f9ed98851'
down_revision = 'f902d969c141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'updated_at')
    # ### end Alembic commands ###
