"""empty message

Revision ID: 4949a4ddb224
Revises: 246f9ed98851
Create Date: 2020-09-06 20:04:52.923669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4949a4ddb224'
down_revision = '246f9ed98851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'latest_article_idx')
    op.drop_column('board', 'latest_article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('latest_article', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('board', sa.Column('latest_article_idx', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
