"""empty message

Revision ID: f902d969c141
Revises: ead5c9af46c9
Create Date: 2020-09-06 17:07:57.747911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f902d969c141'
down_revision = 'ead5c9af46c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'updated_at')
    # ### end Alembic commands ###
